###
POST http://localhost:1234/profesor/registrarse
Content-Type: application/json

{
"nombre": "jose" , 
"apellido": "pertuz", 
"correo": "japertuzd@gmail.com", 
"clave": "194757616", 
"celular":"333333"
}

###

POST http://localhost:1234/profesor/iniciarsesion
Content-Type: application/json

{
"correo": "japertuzd@gmail.com", 
"clave": "194757616"
}

###
POST http://localhost:1234/estudiante/iniciarsesion
Content-Type: application/json

{
  "correo": "yurancydelarosa@gmail.com",
  "clave": "194757616J."
}
###
POST http://localhost:1234/profesor/crear/curso
Content-Type: application/json

{

"titulo":"Introduction to Computer Science",
 "idProfesor": 2,
 "grado": "11",
 "description": "Explore the fundamental concepts of computer science, including algorithms, data structures, and programming languages."
}

###
POST http://localhost:1234/profesor/registrar/estudiante
Content-Type: application/json

{
  "nombre": "Jose",
  "apellido": "Apellido",
  "correo": "aaaaa@example.com",
  "clave": "clave",
  "celular": "324423",
  "idCurso": 8
}

###
GET http://localhost:1234/profesor/cursos/2


###
POST http://localhost:1234/profesor/clases
Content-Type: application/json

{
  "nombreClase": "Clase1",
  "imagenClase": "Image",
   "idCurso": 9,
  "videoNombre": "aasas",
  "videoContenido": "asdsadasdas",
 
  "recursoArchivoLink": "asdasdsadasdasd"
}


###
GET http://localhost:1234/profesor/clases/curso/2


###
GET http://localhost:1234/profesor/cursos/estudiantes/8


###
POST http://localhost:1234/profesor/actividades
Content-Type: application/json

{
  "mensaje": "Deben consultar sobre el medio ambiente",
  "archivo": "Image",
  "idClase": 1
}





###
GET http://localhost:1234/profesor/actividades/1



###
GET http://localhost:1234/profesor/clase/12