###
POST http://localhost:1234/profesor/registrarse
Content-Type: application/json

{
"nombre": "jose" , 
"apellido": "pertuz", 
"correo": "japertuzd@gmail.com", 
"clave": "194757616", 
"celular":"333333"
}

###

POST http://localhost:1234/profesor/iniciarsesion
Content-Type: application/json

{

"correo": "japertuzd@gmail.com", 
"clave": "194757616"
}

###
POST http://localhost:1234/profesor/crear/curso
Content-Type: application/json

{

"titulo":"Introduction to Computer Science",
 "idProfesor": 2,
 "grado": "11",
 "description": "Explore the fundamental concepts of computer science, including algorithms, data structures, and programming languages."
}

###
POST http://localhost:1234/profesor/registrar/estudiante
Content-Type: application/json

{
  "nombre": "Jose",
  "apellido": "Apellido",
  "correo": "sdsd@example.com",
  "clave": "clave",
  "fechaNac": "2000-03-03",
  "sexo": "M",
  "celular": "324423",
  "idCurso": 8
}

###
GET http://localhost:1234/profesor/cursos/2


###
POST http://localhost:1234/profesor/clases
Content-Type: application/json

{
  "nombreClase": "Clase1",
  "imagenClase": "Image",
  "idCurso": 9
}


###
GET http://localhost:1234/profesor/clases/curso/9


###
GET http://localhost:1234/profesor/cursos/estudiantes/8

###
POST http://localhost:1234/profesor/videos
Content-Type: application/json

{
  "nombre": "Clase1",
  "contenido": "Image",
  "idClase": 1
}

###
POST http://localhost:1234/profesor/recursos
Content-Type: application/json

{
  "archivoLink": "cosa",
  "idClase": 1
  
}

###
POST http://localhost:1234/profesor/actividades
Content-Type: application/json

{
  "mensaje": "Deben consultar sobre el medio ambiente",
  "archivo": "Image",
  "idClase": 1
}


###
GET http://localhost:1234/profesor/videos/1
###


###
GET http://localhost:1234/profesor/actividades/1

