-- MySQL Script generated by MySQL Workbench
-- Tue May 14 18:36:48 2024
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema elvis_edukids
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema elvis_edukids
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `elvis_edukids` DEFAULT CHARACTER SET utf8mb3 ;
USE `elvis_edukids` ;

-- -----------------------------------------------------
-- Table `elvis_edukids`.`grado`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `elvis_edukids`.`grado` (
  `idgrado` INT NOT NULL AUTO_INCREMENT,
  `grado` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`idgrado`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `elvis_edukids`.`profesores`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `elvis_edukids`.`profesores` (
  `idprofesos` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NOT NULL,
  `apellido` VARCHAR(45) NOT NULL,
  `correo` VARCHAR(45) NOT NULL,
  `clave` VARCHAR(45) NOT NULL,
  `sexo` VARCHAR(45) NOT NULL,

  `celular` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idprofesos`),
  UNIQUE INDEX `correo_UNIQUE` (`correo` ASC) VISIBLE,
  UNIQUE INDEX `celular_UNIQUE` (`celular` ASC) VISIBLE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `elvis_edukids`.`cursos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `elvis_edukids`.`cursos` (
  `idcursos` INT NOT NULL AUTO_INCREMENT,
  `titulo` VARCHAR(45) NOT NULL,
  `fecha_publicacion` TIMESTAMP NOT NULL,
  `id_profesor` INT NOT NULL,
  `id_grado` INT NOT NULL,
  PRIMARY KEY (`idcursos`),
  INDEX `fk_cursos_profesos1_idx` (`id_profesor` ASC) VISIBLE,
  INDEX `fk_cursos_grado1_idx` (`id_grado` ASC) VISIBLE,
  CONSTRAINT `fk_cursos_grado1`
    FOREIGN KEY (`id_grado`)
    REFERENCES `elvis_edukids`.`grado` (`idgrado`),
  CONSTRAINT `fk_cursos_profesos1`
    FOREIGN KEY (`id_profesor`)
    REFERENCES `elvis_edukids`.`profesores` (`idprofesos`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `elvis_edukids`.`clases`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `elvis_edukids`.`clases` (
  `idclases` INT NOT NULL AUTO_INCREMENT,
  `nombre_clase` VARCHAR(45) NOT NULL,
  `imagen_clase` TEXT NOT NULL,
  `cursos_idcursos` INT NOT NULL,
  PRIMARY KEY (`idclases`),
  INDEX `fk_clases_cursos1_idx` (`cursos_idcursos` ASC) VISIBLE,
  CONSTRAINT `fk_clases_cursos1`
    FOREIGN KEY (`cursos_idcursos`)
    REFERENCES `elvis_edukids`.`cursos` (`idcursos`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `elvis_edukids`.`actividades`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `elvis_edukids`.`actividades` (
  `idrecursos` INT NOT NULL AUTO_INCREMENT,
  `mensaje` VARCHAR(45) NOT NULL,
  `archivo` TEXT NOT NULL,
  `id_clases` INT NOT NULL,
  PRIMARY KEY (`idrecursos`),
  INDEX `fk_recursos_clases1_idx` (`id_clases` ASC) VISIBLE,
  CONSTRAINT `fk_recursos_clases1`
    FOREIGN KEY (`id_clases`)
    REFERENCES `elvis_edukids`.`clases` (`idclases`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `elvis_edukids`.`estudiantes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `elvis_edukids`.`estudiantes` (
  `idestudiantes` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NOT NULL,
  `apellido` VARCHAR(45) NOT NULL,
  `correo` VARCHAR(45) NOT NULL,
  `clave` VARCHAR(45) NOT NULL,
  `fecha_nac` VARCHAR(45) NOT NULL,
  `sexo` VARCHAR(45) NOT NULL,
  `celular` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idestudiantes`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `elvis_edukids`.`calificaciones`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `elvis_edukids`.`calificaciones` (
  `idcalificaciones` INT NOT NULL AUTO_INCREMENT,
  `notas` DOUBLE NOT NULL,
  `id_estudiantes` INT NOT NULL,
  `id_cursos` INT NOT NULL,
  PRIMARY KEY (`idcalificaciones`),
  INDEX `fk_calificaciones_estudiantes1_idx` (`id_estudiantes` ASC) VISIBLE,
  INDEX `fk_calificaciones_cursos1_idx` (`id_cursos` ASC) VISIBLE,
  CONSTRAINT `fk_calificaciones_cursos1`
    FOREIGN KEY (`id_cursos`)
    REFERENCES `elvis_edukids`.`cursos` (`idcursos`),
  CONSTRAINT `fk_calificaciones_estudiantes1`
    FOREIGN KEY (`id_estudiantes`)
    REFERENCES `elvis_edukids`.`estudiantes` (`idestudiantes`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `elvis_edukids`.`estudiantes_x_cursos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `elvis_edukids`.`estudiantes_x_cursos` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `id_estudiantes` INT NOT NULL,
  `id_cursos` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_estudiantes_x_cursos_estudiantes_idx` (`id_estudiantes` ASC) VISIBLE,
  INDEX `fk_estudiantes_x_cursos_cursos1_idx` (`id_cursos` ASC) VISIBLE,
  CONSTRAINT `fk_estudiantes_x_cursos_cursos1`
    FOREIGN KEY (`id_cursos`)
    REFERENCES `elvis_edukids`.`cursos` (`idcursos`),
  CONSTRAINT `fk_estudiantes_x_cursos_estudiantes`
    FOREIGN KEY (`id_estudiantes`)
    REFERENCES `elvis_edukids`.`estudiantes` (`idestudiantes`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `elvis_edukids`.`recursos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `elvis_edukids`.`recursos` (
  `idrecursos` INT NOT NULL AUTO_INCREMENT,
  `archivo_link` TEXT NOT NULL,
  `id_clases` INT NOT NULL,
  PRIMARY KEY (`idrecursos`),
  INDEX `fk_recursos_clases2_idx` (`id_clases` ASC) VISIBLE,
  CONSTRAINT `fk_recursos_clases2`
    FOREIGN KEY (`id_clases`)
    REFERENCES `elvis_edukids`.`clases` (`idclases`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `elvis_edukids`.`videos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `elvis_edukids`.`videos` (
  `idvideos` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NOT NULL,
  `contenido` TEXT NOT NULL,
  `id_clases` INT NOT NULL,
  PRIMARY KEY (`idvideos`),
  INDEX `fk_videos_clases1_idx` (`id_clases` ASC) VISIBLE,
  CONSTRAINT `fk_videos_clases1`
    FOREIGN KEY (`id_clases`)
    REFERENCES `elvis_edukids`.`clases` (`idclases`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
